# Generated by Django 5.2.6 on 2025-09-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ListeningTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md_file', models.TextField()),
                ('audio', models.FileField(upload_to='listening/')),
                ('answers', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ReadingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md_file', models.TextField()),
                ('answers', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField()),
                ('test_type', models.TextField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing')])),
            ],
        ),
        migrations.CreateModel(
            name='UserExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listening_started_at', models.DateTimeField(blank=True, null=True)),
                ('reading_started_at', models.DateTimeField(blank=True, null=True)),
                ('writing_started_at', models.DateTimeField(blank=True, null=True)),
                ('listening_finished', models.BooleanField(default=False)),
                ('reading_finished', models.BooleanField(default=False)),
                ('writing_finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WritingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.TextField()),
                ('question2', models.TextField()),
            ],
        ),
    ]
