# Generated by Django 5.2.6 on 2025-09-28 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md_file', models.TextField()),
                ('audio', models.FileField(upload_to='listening/')),
                ('answers', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ReadingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md_file', models.TextField()),
                ('answers', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='WritingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.TextField()),
                ('question2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_public', models.BooleanField(default=False)),
                ('allowed_users', models.ManyToManyField(related_name='allowed_exams', to=settings.AUTH_USER_MODEL)),
                ('joined_users', models.ManyToManyField(blank=True, null=True, related_name='exams', to=settings.AUTH_USER_MODEL)),
                ('listening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.listeningtest')),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.readingtest')),
                ('writing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.writingtest')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField()),
                ('test_type', models.TextField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing')])),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exam.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listening_started_at', models.DateTimeField(blank=True, null=True)),
                ('reading_started_at', models.DateTimeField(blank=True, null=True)),
                ('writing_started_at', models.DateTimeField(blank=True, null=True)),
                ('listening_finished', models.BooleanField(default=False)),
                ('reading_finished', models.BooleanField(default=False)),
                ('writing_finished', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exam.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
