# Generated by Django 5.2.6 on 2025-10-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_exam_joined_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningtest',
            name='auto_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readingtest',
            name='auto_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='writingtest',
            name='auto_failed',
            field=models.BooleanField(default=False),
        ),
    ]
