# Generated by Django 5.2.6 on 2025-09-25 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_remove_exam_exam_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
