# Generated by Django 5.2.6 on 2025-10-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_listeningtest_auto_failed_readingtest_auto_failed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningtest',
            name='auto_failed',
        ),
        migrations.RemoveField(
            model_name='readingtest',
            name='auto_failed',
        ),
        migrations.RemoveField(
            model_name='writingtest',
            name='auto_failed',
        ),
        migrations.AddField(
            model_name='testresult',
            name='auto_failed',
            field=models.BooleanField(default=False),
        ),
    ]
