# Generated by Django 5.2.6 on 2025-10-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_remove_listeningtest_auto_failed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingtest',
            name='graph',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
