# Generated by Django 5.2.6 on 2025-10-05 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_writingtest_graph'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='finished_users',
            field=models.ManyToManyField(blank=True, related_name='finished_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exam',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_exams', to=settings.AUTH_USER_MODEL),
        ),
    ]
